on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'
name: Make Index
jobs:
  makeIndex:
    name: makeIndex
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@main
    - run: |
        bin/makeindex.ps1
    - uses: EndBug/add-and-commit@v9
      with:
        add: 'README.md'
        new_branch: main
        author_name: xinchenliu998
        author_email: xinchenliu998@163.com
        message: '(chore): update app index [scoop skip]'
